DROP TABLE IF EXISTS TEST.SAMPLE_TABLE;

CREATE TABLE IF NOT EXISTS TEST.SAMPLE_TABLE (
ORG_ID CHAR(15) NOT NULL,
STATUS VARCHAR
CONSTRAINT PK PRIMARY KEY (ORG_ID)
) VERSIONS=1,MULTI_TENANT=FALSE,REPLICATION_SCOPE=1,TTL=31536000;

CREATE TABLE IF NOT EXISTS TEST.SAMPLE_TABLE (
ORG_ID CHAR(15) NOT NULL,
STATUS VARCHAR
CONSTRAINT PK PRIMARY KEY (ORG_ID)
) VERSIONS=1,MULTI_TENANT=FALSE,REPLICATION_SCOPE=1,TTL=31536000;