global:
  email-reply-to: phoenixdatabaseteam@salesforce.com,bigdatascalemultitenancy@salesforce.com
  node-type: c5d.18xlarge
  timeout: 420
  production-branches:
    - 5.2-sfdc-13
stages:
  integration-test:
    - step:
        name: mvn-verify
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_centos7_jdk8
        commands:
          - mvn -Pcodecoverage verify -Dmaven.test.failure.ignore=true -Dsurefire.testFailureIgnore=true
          - mvn jacoco:report-aggregate
