sonar.sources=phoenix-core-client/src/main, phoenix-core-server/src/main, phoenix-hbase-compat-2.5.4/src/main
sonar.tests=phoenix-core/src/test, phoenix-core/src/it
sonar.java.binaries=**/target/classes
sonar.java.libraries=**/target/*.jar
sonar.java.test.binaries=phoenix-core/target/test-classes
sonar.coverage.exclusions=phoenix-assembly/**,phoenix-client-parent/**,phoenix-mapreduce-byo-shaded-hbase/**,phoenix-pherf/**,phoenix-server/**,phoenix-tracing-webapp/**,**/*.cpp,**/*.c,**/*.py,**/*.php,**/*.proto,**/generated/**/*
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml, **/target/site/jacoco-aggregate/jacoco.xml
sonar.junit.reportPaths=phoenix-core/target/surefire-reports
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
