CREATE TABLE IF NOT EXISTS PHERF.PHOENIX_FUNCTIONAL_SIGNOFF_TABLE (
    VAL_STRING VARCHAR,
    HOST CHAR(2) NOT NULL,
    DOMAIN VARCHAR NOT NULL,
    STATS.ACTIVE_VISITOR INTEGER
    CONSTRAINT PK PRIMARY KEY
    (
        VAL_STRING,
        HOST,
        DOMAIN
    )
)